### ISSUE TITLE
50 steps of 1 class

### ISSUE THREAD

**Issue by arthurdouillard** [JoyHuYY1412/DDE_CIL#1]
Hey,

Congrats on your paper, it's very interesting.

I just had a quick question, did you try longer setting such as in PODNet, with 50 steps of 1 class each for CIFAR100/ImageNet100? This is where the forgetting is the most important and thus wondered if DCE could help a lot there.

Thanks :)

**Comment by JoyHuYY1412** [comment]
> Hey,
> 
> Congrats on your paper, it's very interesting.
> 
> I just had a quick question, did you try longer setting such as in PODNet, with 50 steps of 1 class each for CIFAR100/ImageNet100? This is where the forgetting is the most important and thus wondered if DCE could help a lot there.
> 
> Thanks :)

I tried on CIFAR but the result was not so good as in 5 steps or 10 steps. I think the reasons are two-fold: 1) the baseline like your work is pretty well in such a setting; 2) my work tends to sacrifice novel classes and thus finds the long-run hard to handle. 

Hope you enjoy your research in anti-forgetting and thank you for your help!

**Comment by arthurdouillard** [comment]
Thank for the info!
