### ISSUE TITLE
Report an error when run "cifar100-class-incremental/run.sh"

### ISSUE THREAD

**Issue by Dingseewhole** [JoyHuYY1412/DDE_CIL#2]
my environment is torch==0.4.1 torchvision==0.9.0 python=3.7
when I use the shell script _cifar100-class-incremental/run.sh_ to run the example, it report error:

1.`  File "eval_cumul_acc_TDE.py", line 98, in <module>
    input_data = evalset.test_data
AttributeError: 'CIFAR100' object has no attribute 'test_data'`
2. ModuleNotFoundError: No module named 'utils_incremental.incremental_train_and_eval_MS_TDE'
3.ModuleNotFoundError: No module named 'incremental_train_and_eval_d_constrain'

I think maybe the version of torch cause the **First** error, so I also try the environment with torch==1.8 torchvision==0.9.0 python=3.7,  but it doesn't helpful.
And I also can't find the modules in **2,3**, are they necessary?

**Comment by JoyHuYY1412** [comment]
1. Yes. See https://github.com/HobbitLong/RepDistiller/issues/4 about different versions of torchvision when handling CIFAR. You can also use `self.data` and `self.targets` instead.

2. and 3. They are not necessary. Sorry about that. Those were some testing codes that I forgot to delete. I already updated the code.

**Comment by Dingseewhole** [comment]
> 1. Yes. See [HobbitLong/RepDistiller#4](https://github.com/HobbitLong/RepDistiller/issues/4) about different versions of torchvision when handling CIFAR. You can also use `self.data` and `self.targets` instead.
> 2. and 3. They are not necessary. Sorry about that. Those were some testing codes that I forgot to delete. I already updated the code.

thank you for reply.
If you can post the full information in READ.me, such as numpy-version torchvision-version, it will be very helpful!
