### ISSUE TITLE
Implementation of PODNet 

### ISSUE THREAD

**Issue by balaji-kyra** [JoyHuYY1412/DDE_CIL#3]
Hi 

This is a very nice paper. Congratulations! In the experiments, the paper compares results with LUCIR and PODNet as state-of-the-art incremental methods. The code has baseline LUCIR implementation. Will you also include PODNet implementation for comparison?

Thanks

Balaji

**Comment by JoyHuYY1412** [comment]
> Hi
> 
> This is a very nice paper. Congratulations! In the experiments, the paper compares results with LUCIR and PODNet as state-of-the-art incremental methods. The code has baseline LUCIR implementation. Will you also include PODNet implementation for comparison?
> 
> Thanks
> 
> Balaji

Hi Balaji, thank you for your attention. 

Since my PODNet implementation is not very clean, I only release the LUCIR implementation currently. I will sort it out later on. You will also find it easy to implement yourself once you understand the mechanism.

**Comment by libo-huang** [comment]
> > Hi
> > This is a very nice paper. Congratulations! In the experiments, the paper compares results with LUCIR and PODNet as state-of-the-art incremental methods. The code has baseline LUCIR implementation. Will you also include PODNet implementation for comparison?
> > Thanks
> > Balaji
> 
> Hi Balaji, thank you for your attention.
> 
> Since my PODNet implementation is not very clean, I only release the LUCIR implementation currently. I will sort it out later on. You will also find it easy to implement yourself once you understand the mechanism.

three years later...
