### ISSUE TITLE
Quick question about Implementation on  cifar100

### ISSUE THREAD

**Issue by Dingseewhole** [JoyHuYY1412/DDE_CIL#4]
Thanks for this interesting paper. I have a quick question after comparing the paper and the code.
In the paper, I see  "For the proposed Distillation of Colliding Effect (DCE), we used cosine distance to measure the similarity between images." But in the **incremental_train_and_eval_DCE_MR_LF_TDE.py** I see the code use L2 distance to generate the match_id at **line 146** and function **pdist**
Is this dis_z was used to select knn inputs? If it is that, why in code is **L2_dist** but not **cos_dist**?

**Comment by JoyHuYY1412** [comment]
> Thanks for this interesting paper. I have a quick question after comparing the paper and the code.
> In the paper, I see "For the proposed Distillation of Colliding Effect (DCE), we used cosine distance to measure the similarity between images." But in the **incremental_train_and_eval_DCE_MR_LF_TDE.py** I see the code use L2 distance to generate the match_id at **line 146** and function **pdist**
> Is this dis_z was used to select knn inputs? If it is that, why in code is **L2_dist** but not **cos_dist**?

Thank you for pointing it out! I meant to write "euclidean" distance... 

Sorry for bringing your confusion! You can also try cosine distance, and I think maybe you can get slightly better results.

**Comment by Dingseewhole** [comment]
Thanks for the quick reply!
 So in the code  **incremental_train_and_eval_DCE_MR_LF_TDE.py** and the function **pdist**, you actually use _**euclidean distance**_ to select the KNN match_id, which means the topk **smallest** euclidean distance inputs will be sellected as match_id. 
Am I right?

**Comment by JoyHuYY1412** [comment]
> Thanks for the quick reply!
> So in the code **incremental_train_and_eval_DCE_MR_LF_TDE.py** and the function **pdist**, you actually use _**euclidean distance**_ to select the KNN match_id, which means the topk **smallest** euclidean distance inputs will be sellected as match_id.
> Am I right?

Yes! You are right ^_^
