### ISSUE TITLE
 error : AttributeError: module 'torch' has no attribute 'flatten'

### ISSUE THREAD

**Issue by miss-rain** [JoyHuYY1412/DDE_CIL#6]
my pytorch vision is 0.4.0,
 when i run run.sh, 
 i meet error : AttributeError: module 'torch' has no attribute 'flatten'

Could you help me?

**Comment by JoyHuYY1412** [comment]
> AttributeError: module 'torch' has no attribute 'flatten'

Hi, don't worry about it. You can use `.view()` to reshape the tensor or other similar ways.
