### ISSUE TITLE
Results of PODNet w\ DDE

### ISSUE THREAD

**Issue by Kingofolk** [JoyHuYY1412/DDE_CIL#7]
hello!
Thank you for your great work! I am seeking for the results of PODNet w\ DDE under T=25 and T=50 settings. But I found that the code of PODNet w\ DDE is not included in this repo. Could you please offer me the results or just release the related code?
Thanks a lot
Kingofolk

**Comment by JoyHuYY1412** [comment]
[PODNet_TDE.zip](https://github.com/JoyHuYY1412/DDE_CIL/files/9595266/PODNet_TDE.zip)
Hi, thank you for your interest! I didn't report the result of so many steps. In my previous experiments, the results are not higher than PODnet. The modified code is updated.

**Comment by 1259666087** [comment]
> [PODNet_TDE.zip](https://github.com/JoyHuYY1412/DDE_CIL/files/9595266/PODNet_TDE.zip) Hi, thank you for your interest! I didn't report the result of so many steps. In my previous experiments, the results are not higher than PODnet. The modified code is updated.

Is there any DDE content in this code? If so, which files have been modified?

**Comment by 1259666087** [comment]
> [PODNet_TDE.zip](https://github.com/JoyHuYY1412/DDE_CIL/files/9595266/PODNet_TDE.zip) Hi, thank you for your interest! I didn't report the result of so many steps. In my previous experiments, the results are not higher than PODnet. The modified code is updated.

Hello, I read your code files about podnet but didn’t find the part about DDE. Which files did you modify?
